name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ "Consumer", "Producer" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      # 1. Install system deps, including libpqxx-dev
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libpq-dev \
            libpqxx-dev \
            libssl-dev \
            zlib1g-dev \
            libmosquitto-dev \
            librabbitmq-dev

      # 2. Clean up any accidental submodule traces
      - name: Remove accidental build submodules
        run: |
          rm -f .gitmodules || true
          git submodule deinit -f . || true
          git config --global --add safe.directory $PWD

      # 3. If someone committed local _deps/libpqxx-src, wipe it here
      - name: Purge accidental vendored libpqxx
        run: |
          rm -rf Consumer/build-ci/_deps/libpqxx-src || true
          rm -rf Consumer/_deps/libpqxx-src || true
          rm -rf build-ci/_deps/libpqxx-src || true

      # 4. Show what pqxx the runner has
      - name: Show pqxx pkg-config
        run: |
          pkg-config --modversion libpqxx || true
          pkg-config --cflags --libs libpqxx || true

      # 5. Clean project build dir
      - name: Clean build dir
        run: rm -rf ${{ matrix.project }}/build-ci

      # 6. Configure (now it must find system libpqxx)
      - name: Configure ${{ matrix.project }}
        run: cmake -S ${{ matrix.project }} -B ${{ matrix.project }}/build-ci -DCMAKE_BUILD_TYPE=Release

      # 7. Build
      - name: Build ${{ matrix.project }}
        run: cmake --build ${{ matrix.project }}/build-ci --config Release -- -j$(nproc)

      # 8. Test
      - name: Test ${{ matrix.project }}
        run: ctest --output-on-failure
        working-directory: ${{ matrix.project }}/build-ci
