name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Consumer", "Producer" ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          
      - name: Remove accidental build submodules
        run: |
          rm -f .gitmodules
          git submodule deinit -f .
          git config --global --add safe.directory $PWD

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libpq-dev \
            libpqxx-dev \
            libssl-dev \
            zlib1g-dev \
            libmosquitto-dev \
            librabbitmq-dev

      - name: Show pqxx pkg-config
        run: |
          pkg-config --modversion libpqxx || true
          pkg-config --cflags --libs libpqxx || true

      - name: Clean build dir
        run: rm -rf ${{ matrix.project }}/build-ci

      - name: Configure ${{ matrix.project }}
        run: cmake -S ${{ matrix.project }} -B ${{ matrix.project }}/build-ci -DCMAKE_BUILD_TYPE=Release

      - name: Build ${{ matrix.project }}
        run: cmake --build ${{ matrix.project }}/build-ci --config Release

      - name: Test ${{ matrix.project }}
        run: ctest --output-on-failure
        working-directory: ${{ matrix.project }}/build-ci
